In [1]:
import pandas as pd
from datetime import datetime

# pd.set_option('display.max_rows', 30)

In [2]:
df = pd.read_csv('targetfile/StatementCSV_20231110_2357.csv')
df

,Ticket,OrderType,OrderSymbol,OrderLots,OrderOpenTime,OrderOpenPrice,OrderCloseTime,OrderClosePrice,OrderProfitInPips,OrderCommission,OrderSwap,OrderProfit,TradeProfit,OrderMagicNumber,OrderComment,OrderCommentShort
0,21194,BUY,GOLD,0.01,2023.11.06 01:05,1991.86,2023.11.06 01:42,1988.53,-33.3,0,0,-498,-498,100,100pips_buy_1,10
1,21195,BUY,GOLD,0.01,2023.11.06 01:05,1991.86,2023.11.06 02:36,1989.45,-24.1,0,0,-360,-360,200,200pips_buy_1,20
2,21196,BUY,GOLD,0.01,2023.11.06 01:05,1991.86,2023.11.06 02:59,1991.55,-3.1,0,0,-46,-46,400,400pips_buy_1,40
3,21197,BUY,GOLD,0.01,2023.11.06 01:05,1991.86,2023.11.06 03:30,1992.49,6.3,0,0,94,94,500,500pips_buy_1,50
4,21198,BUY,GOLD,0.01,2023.11.06 01:05,1991.86,2023.11.06 02:56,1990.43,-14.3,0,0,-214,-214,300,300pips_buy_1,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,141139,BUY,GOLD,0.02,2023.11.10 20:51,1936.18,2023.11.10 22:15,1936.21,0.3,0,0,9,9,100,100pips_buy_2,10
2451,141261,BUY,GOLD,0.02,2023.11.10 21:00,1935.52,2023.11.10 23:19,1937.42,19.0,0,0,576,576,200,200pips_buy_2,20
2452,141335,SELL,GOLD,0.02,2023.11.10 21:09,1936.83,2023.11.10 21:40,1935.81,10.2,0,0,309,309,100,100pips_sell_2,10
2453,141773,BUY,GOLD,0.03,2023.11.10 22:01,1935.20,2023.11.10 22:15,1936.22,10.2,0,0,464,464,100,100pips_buy_3,10
2454,141969,BUY,GOLD,0.01,2023.11.10 22:15,1936.56,2023.11.10 23:22,1937.61,10.5,0,0,159,159,100,100pips_buy_1,10

In [6]:
df['EntryTime'] = pd.to_datetime(df.OrderOpenTime)
df['CloseTime'] = pd.to_datetime(df.OrderCloseTime)
df['OrderOpenYear'] = pd.to_datetime(df['OrderOpenTime']).dt.year
df['OrderOpenMonth'] = pd.to_datetime(df['OrderOpenTime']).dt.month
df['OrderOpenDay'] = pd.to_datetime(df['OrderOpenTime']).dt.day
df['OrderOpenHour'] = pd.to_datetime(df['OrderOpenTime']).dt.hour

df['HaveTime'] = df['CloseTime'] - df['EntryTime']
df['OrderGroup'] = df['OrderComment'].str[:11]
df['Count'] = 0

groups = df.groupby(df.OrderGroup)[['OrderType', 'OrderLots', 'EntryTime', 'OrderOpenPrice', 'OrderClosePrice', 'CloseTime', 'OrderComment', 'HaveTime', 'Count']]

pips100L_df = groups.get_group("100pips_buy")
pips200L_df = groups.get_group('200pips_buy')
pips300L_df = groups.get_group('300pips_buy')
pips400L_df = groups.get_group('400pips_buy')
pips500L_df = groups.get_group('500pips_buy') 

pips100S_df = groups.get_group("100pips_sel")
pips200S_df = groups.get_group("200pips_sel") 
pips300S_df = groups.get_group("300pips_sel")
pips400S_df = groups.get_group("400pips_sel")
pips500S_df = groups.get_group("500pips_sel")

In [7]:
def GetCounts(x):
    

pips500S_df

,OrderType,OrderLots,EntryTime,OrderOpenPrice,OrderClosePrice,CloseTime,OrderComment,HaveTime,Count
8,SELL,0.01,2023-11-06 01:05:00,1991.33,1987.43,2023-11-06 04:54:00,500pips_sell_1,0 days 03:49:00,0
63,SELL,0.02,2023-11-06 03:30:00,1992.49,1987.44,2023-11-06 04:54:00,500pips_sell_2,0 days 01:24:00,0
95,SELL,0.01,2023-11-06 04:54:00,1986.99,1983.09,2023-11-06 05:42:00,500pips_sell_1,0 days 00:48:00,0
100,SELL,0.02,2023-11-06 05:07:00,1988.08,1983.04,2023-11-06 05:42:00,500pips_sell_2,0 days 00:35:00,0
123,SELL,0.01,2023-11-06 05:42:00,1982.80,1983.14,2023-11-06 17:35:00,500pips_sell_1,0 days 11:53:00,0
...,...,...,...,...,...,...,...,...,...
2354,SELL,0.02,2023-11-10 17:37:00,1942.28,1938.32,2023-11-10 18:24:00,500pips_sell_2,0 days 00:47:00,0
2359,SELL,0.03,2023-11-10 17:37:00,1943.32,1938.31,2023-11-10 18:24:00,500pips_sell_3,0 days 00:47:00,0
2397,SELL,0.01,2023-11-10 18:24:00,1937.96,1935.18,2023-11-10 20:24:00,500pips_sell_1,0 days 02:00:00,0
2399,SELL,0.02,2023-11-10 18:25:00,1939.18,1935.18,2023-11-10 20:24:00,500pips_sell_2,0 days 01:59:00,0
2414,SELL,0.03,2023-11-10 18:52:00,1940.22,1935.19,2023-11-10 20:24:00,500pips_sell_3,0 days 01:32:00,0

時間帯ごとのエントリー数

In [4]:
multi_df2.groupby(['Year', 'Month', 'Day', 'Hour']).count()

NameError: name 'multi_df2' is not defined